server:
  port: 7004

spring:
  application:
    name: API-GATEWAY
  # setting applicatio type to reactive as, after adding spring-boot-starter-web dependency,there is  conflict between
  # Spring MVC & spring cloud gateway.as spring cloud gateway is reactive , so either remove dependency or add this.
  main:
    web-application-type: reactive

# We can use this configuration or define in MYCONFIG class

#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id : USER-SERVICE
#            uri: lb://USER-SERVICE
#            predicates:
#              - Path=/users/**
#
#          - id: HOTEL-SERVICE
#            uri: lb://HOTEL-SERVICE
#            predicates:
#              - Path=/hotels/**
#
#          - id: HOTEL-SERVICE
#            uri: lb://HOTEL-SERVICE
#            predicates:
#              - Path=/staff/**
#
#          - id: RATING-SERVICE
#            uri: lb://RATING-SERVICE
#            predicates:
#              - Path=/ratings/**

  config:
    import: optional:configserver:http://localhost:7005

# READ ABOUT FAIL FAST

#  cloud:
#    config:
#      fail-fast: false

#NOW we importing these configuration form CONFIG-SERVER

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://localhost:7003/eureka

#logging:
#  level:
#    org:
#      springframework : DEBUG

#Okta configuration for API GATEWAY
okta:
  oauth2:
    issuer: https://dev-30011393.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaet9udkgGpvIBYw5d7
    client-secret: H6kOPhNaj9z9NlKbwASj2KkLX4M46N8OEQla7dq0oXuno0yPVf1mqfHpGd6EqFs1
    scopes: openid, profile , email, offline_access

#--------------------> You can use Above Configuration or the Below one Both are same.

#spring:
#  security:
#    oauth2:
#      resourceserver: #defining a bean of type 'org.springframework.security.oauth2.jwt.ReactiveJwtDecoder' or Can be defined in Security Config class.
#        jwt:
#          issuer-uri: https://dev-30011393.okta.com/oauth2/default
#      client:
#        registration:
#          okta:
#            client-id: 0oaet9udkgGpvIBYw5d7
#            client-secret: H6kOPhNaj9z9NlKbwASj2KkLX4M46N8OEQla7dq0oXuno0yPVf1mqfHpGd6EqFs1
#            scope: openid, profile , email, offline_access
#        provider:
#          okta:
#            issuer-uri: https://dev-30011393.okta.com/oauth2/default

