server:
  port: 7001

spring:

  application:
    name: Hotel-Service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: shashwat
    url: jdbc:mysql://localhost:3306/hotelmicroservices

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  config:
    import: optional:configserver:http://localhost:7005

#NOW we importing these configuration form CONFIG-SERVER

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://localhost:7003/eureka