server:
  port: 7001

spring:

  application:
    name: Hotel-Service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: shashwat
    url: jdbc:mysql://localhost:3306/hotelmicroservices

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  config:
    import: optional:configserver:http://localhost:7005

#------->Okta configuration for HOTEL SERVICE

#  security:
#    oauth2:
#      resourceserver: # defining a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' or can be defined in Config Class
#        jwt:
#          issuer-uri: https://dev-30011393.okta.com/oauth2/default

#--------------------> You can use Above Configuration or the Below one Both are same.

okta:
  oauth2:
    issuer: https://dev-30011393.okta.com/oauth2/default
    audience: api://default

#------->NOW we importing these configuration form CONFIG-SERVER

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://localhost:7003/eureka