server:
  port: 7000
spring:

  application:
    name: User-Service

  profiles:
    active: default

  datasource:
    url: jdbc:mysql://localhost:3306/usermicroservices
    username: root
    password: shashwat
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:7005


#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect


#NOW we importing these configuration form CONFIG-SERVER

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://localhost:7003/eureka