server:
  port: 7000
spring:

  application:
    name: User-Service

  profiles:
    active: default

  datasource:
    url: jdbc:mysql://localhost:3306/usermicroservices
    username: root
    password: shashwat
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:7005

# CONFIGURATION of  USER SERVICE TO ACT as CLIENT
  security:
    oauth2:
      resourceserver:
        jwt:   # defining a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' or can be defined in Config Class
          issuer-uri: https://dev-30011393.okta.com/oauth2/default
      client:
        registration:
          my-internal-client :
            provider: okta
            authorization-grant-type: client_credentials      # MUST READ
            scope: internal
            client-id: 0oaet9udkgGpvIBYw5d7
            client-secret: H6kOPhNaj9z9NlKbwASj2KkLX4M46N8OEQla7dq0oXuno0yPVf1mqfHpGd6EqFs1
        provider:
          okta:
            issuer-uri: https://dev-30011393.okta.com/oauth2/default
#            token-uri: https://dev-30011393.okta.com/oauth2/default/v1/token


#Okta configuration for USER SERVICE
okta:
  oauth2:
    issuer: https://dev-30011393.okta.com/oauth2/default
    audience: api://default


#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect


#NOW we importing these configuration form CONFIG-SERVER

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://localhost:7003/eureka

# Configuring ACTUATORS
management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  ratelimiter:
    instances:
      UserRatingHotelRateLimiter:
        register-health-indicator: false
        timeout-duration:
          seconds: 0
        limit-refresh-period:
          seconds: 10
        limit-for-period: 2
  retry:
    instances:
      UserRatingHotelRetry :
        max-attempts: 3
        wait-duration:
          seconds: 3

  circuitbreaker:
    instances:
      UserRatingHotelCircuitBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 6
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

